version: '3.8'
services:
  test_gtd:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlnet/test_gtd
    volumes:
      - ./:/app
    depends_on:
      - mysqlnet

  mysqlnet:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=test_gtd
      - MYSQL_PASSWORD=test_gtd
      - MYSQL_DATABASE=test_gtd
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config: